---
---
- hosts: docker
  become: true
  tasks: 
   - name: Update Cache
    apt:
      update_cache: true
      
  - name: install JDK 17 #Needed to connect Docker server to Jenkins
    apt:
      name: openjdk-17-jdk
      state: present
      
  - name: install Docker
    apt:
      name: docker
      state: present
      update_cache: true

  - name: Change ownership for docker.
    file:
      path: /home/docker/docker
      owner: docker
      group: docker
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
  
  - name: start docker
    systemd:
      name: docker
      state: started

#Ansible user
#---
#- hosts: docker
#  become: true
#  tasks:         
#  - name: install JDK 11
#    apt:
#      name: openjdk-17-jdk
#      state: present
#      
#  - name: install Docker
#    apt:
#      name: docker
#      state: present
#      update_cache: true
#
#  - name: Change ownership of docker to the Ansible user.
#    file:
#      path: /home/ansible/docker
#      owner: ansible
#      group: ansible
#      mode: "u+rwx,g+rx,o=rx"
#      recurse: yes
#  
#  - name: start docker
#    systemd:
#      name: docker
#      state: started

